### ISSUE TITLE
Support for ALL consumers/providers for webhook provisioning

### ISSUE THREAD

**Issue by garry-jeromson** [pactflow/terraform#2]
In the webhooks settings dialog on PactFlow, it's possible to select `ALL` as an option for both consumer and provider when configuring the webhook. On first glance at the examples and documentation, this isn't currently possible using the Terraform provider - is it actually possible and just undocumented? And if not, is it planned?

**Comment by mefellows** [comment]
Thanks! I'll look into this tonight

**Comment by mefellows** [comment]
To match `ALL` consumers or `ALL` providers, you simply omit the consumer/provider, and it will match all for the given role.

From https://docs.pact.io/pact_broker/advanced_topics/api_docs/webhooks#creating

> Both provider and consumer are optional - omitting either indicates that any pacticipant in that role will be matched. 

I'll update the README now.
