### ISSUE TITLE
Specifying contract_changed_event as a webhook event causes a bad request error

### ISSUE THREAD

**Issue by garry-jeromson** [pactflow/terraform#3]
## Description

When creating a `pact_webhook` resource, supplying `contract_changed_event` (as suggested in the examples and documentation) in the list of values for the `event` attribute leads to an "Error: bad request" failure when running a `terraform apply`:

```
resource "pact_webhook" "provider_verification_published" {
...
  events     = ["contract_event_changed"]
}
```

At first glance, it would seem like `contract_changed_event` is the wrong event type value to pass to the API; it's [inconsistent with the broker client](https://github.com/pact-foundation/pact_broker-client/blob/d34e55f08a4bc7549bb45143bffb1d1246b3927c/lib/pact_broker/client/cli/broker.rb), which uses the value `contract_content_changed`.

**Comment by garry-jeromson** [comment]
The cause of the issue is more or less confirmed by the webhook API docs: https://docs.pact.io/pact_broker/advanced_topics/api_docs/webhooks.

**Comment by mefellows** [comment]
`v0.0.3` is currently on the way out with this fix (see https://travis-ci.org/github/pactflow/terraform/builds/698870592).
