### ISSUE TITLE
Support for provider_verification_failed event 

### ISSUE THREAD

**Issue by lukaszczechowski** [pactflow/terraform#9]
Would it be possible to include support for **_provider_verification_failed_** event as described in [Webhook docs](https://docs.pact.io/pact_broker/webhooks)? 

I'm not sure but I believe that the client used under the hood supports this kind of event and it is only a matter of extending the following list:
https://github.com/pactflow/terraform/blob/dda87a391c9780948fca285a9d6337dc17f27344/resource_webhook.go#L18

**Comment by mefellows** [comment]
Yep, I'll get this out tomorrow! Thanks.

**Comment by mefellows** [comment]
Release on the way (v0.1.0).

**Comment by lukaszczechowski** [comment]
Thanks @mefellows for (lighting fast) delivering of a  fix :) 
I've got one remark though. The following method is implemented in a way which requires the input array **_s_** to be initially sorted.
```
func stringContains(s []string, searchterm string) bool {
	i := sort.SearchStrings(s, searchterm)
	return i < len(s) && s[i] == searchterm
}
```
Currently, if you use the new type of the event (**provider_verification_failed**) it won't be validated because returned index **_i_** doesn't match the index of the input array **_s_**.
As a quick fix I propose to reorder the **_allowedEvents_** array:
```
var allowedEvents = []string{
	"contract_content_changed",
	"contract_published",
	"provider_verification_failed",
	"provider_verification_published",
	"provider_verification_succeeded",
}

```

**Comment by mefellows** [comment]
Ah! Good pickup, apologies for that.

I've just pushed out a minor fix to address that issue (it will now sort the input array too).
